POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCXVCJ9.eyJ1c2VybmFtZSI6InRvc2loeXZhc2FsYXNhbmExIiwiaWQiOiI1ZGQ5OGY0ODA0YjVmMjE2ZDQzYTQwMzIiLCJpYXQiOjE1NzQ1NDgxNTN9.3D7QI6ZmJIjRqB6CEnz8dCLzDmEspXgj0g_os-1ovx8

{
  "title": "otsikko4",
  "author": "Jere T",
  "url": "testsite.net",
  "likes": 3
}